openapi: 3.0.1
info:
  title: '@jupiterone/graph-manageengine-endpoint-central'
  description: >-
    An integration and graph conversion project for ManageEngine Endpoint
    Central
  x-cortex-git:
    github:
      repository: JupiterOne/graph-manageengine-endpoint-central
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-manageengine-endpoint-central'
  x-cortex-service-groups:
    - tier-4
